### ISSUE TITLE
Can not install diso 

### ISSUE THREAD

**Issue by phongnhhn92** [SarahWeiii/diso#11]
Hi, I have this error when I try to install the package

```
ubuntu@6c82abd23c18:~$ pip install diso
Collecting diso
  Using cached diso-0.1.4.tar.gz (24 kB)
  Preparing metadata (setup.py) ... done
Collecting trimesh (from diso)
  Using cached trimesh-4.4.3-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: numpy>=1.20 in ./miniconda3/envs/dg-mesh/lib/python3.9/site-packages (from trimesh->diso) (1.26.4)
Using cached trimesh-4.4.3-py3-none-any.whl (695 kB)
Building wheels for collected packages: diso
  Building wheel for diso (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [159 lines of output]
      sources: ['src/pybind.cpp', 'src/cumc.cu', 'src/cudualmc.cu']
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/diso
      copying diso/__init__.py -> build/lib.linux-x86_64-cpython-39/diso
      running build_ext
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/utils/cpp_extension.py:428: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'diso._C' extension
      creating /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/build/temp.linux-x86_64-cpython-39
      creating /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/build/temp.linux-x86_64-cpython-39/src
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/utils/cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
      If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
        warnings.warn(
      Emitting ninja build file /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/build/temp.linux-x86_64-cpython-39/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/3] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/build/temp.linux-x86_64-cpython-39/src/cumc.o.d -DWITH_CUDA -Isrc -I/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include -I/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/TH -I/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/ubuntu/miniconda3/envs/dg-mesh/include/python3.9 -c -c /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/src/cumc.cu -o /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/build/temp.linux-x86_64-cpython-39/src/cumc.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++17
      /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/src/cumc.cu(161): warning #177-D: variable "cumc::problematicConfigs" was declared but never referenced
      
      [2/3] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/build/temp.linux-x86_64-cpython-39/src/cudualmc.o.d -DWITH_CUDA -Isrc -I/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include -I/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/TH -I/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/ubuntu/miniconda3/envs/dg-mesh/include/python3.9 -c -c /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/src/cudualmc.cu -o /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/build/temp.linux-x86_64-cpython-39/src/cudualmc.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++17
      [3/3] c++ -MMD -MF /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/build/temp.linux-x86_64-cpython-39/src/pybind.o.d -pthread -B /home/ubuntu/miniconda3/envs/dg-mesh/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/ubuntu/miniconda3/envs/dg-mesh/include -I/home/ubuntu/miniconda3/envs/dg-mesh/include -fPIC -O2 -isystem /home/ubuntu/miniconda3/envs/dg-mesh/include -fPIC -DWITH_CUDA -Isrc -I/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include -I/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/TH -I/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/ubuntu/miniconda3/envs/dg-mesh/include/python3.9 -c -c /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/src/pybind.cpp -o /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/build/temp.linux-x86_64-cpython-39/src/pybind.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
      FAILED: /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/build/temp.linux-x86_64-cpython-39/src/pybind.o
      c++ -MMD -MF /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/build/temp.linux-x86_64-cpython-39/src/pybind.o.d -pthread -B /home/ubuntu/miniconda3/envs/dg-mesh/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/ubuntu/miniconda3/envs/dg-mesh/include -I/home/ubuntu/miniconda3/envs/dg-mesh/include -fPIC -O2 -isystem /home/ubuntu/miniconda3/envs/dg-mesh/include -fPIC -DWITH_CUDA -Isrc -I/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include -I/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/TH -I/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/ubuntu/miniconda3/envs/dg-mesh/include/python3.9 -c -c /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/src/pybind.cpp -o /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/build/temp.linux-x86_64-cpython-39/src/pybind.o -O3 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
      In file included from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/ATen/core/TensorBase.h:14:0,
                       from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/ATen/core/TensorBody.h:38,
                       from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/ATen/core/Tensor.h:3,
                       from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/ATen/Tensor.h:3,
                       from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                       from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                       from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                       from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                       from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                       from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                       from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/extension.h:5,
                       from /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/src/pybind.cpp:3:
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/c10/util/C++17.h:13:2: error: #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 9 or later."
       #error \
        ^~~~~
      In file included from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/Exceptions.h:12:0,
                       from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/python.h:11,
                       from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/extension.h:9,
                       from /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/src/pybind.cpp:3:
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<cumc::CUMC<double, int> >’:
      /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/src/pybind.cpp:421:60:   required from here
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/pybind11/pybind11.h:1555:7: warning: ‘pybind11::class_<cumc::CUMC<double, int> >’ declared with greater visibility than the type of its field ‘pybind11::class_<cumc::CUMC<double, int> >::<anonymous>’ [-Wattributes]
       class class_ : public detail::generic_type {
             ^~~~~~
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/pybind11/pybind11.h:1555:7: warning: ‘pybind11::class_<cumc::CUMC<double, int> >’ declared with greater visibility than its base ‘pybind11::detail::generic_type’ [-Wattributes]
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<cumc::CUMC<float, int> >’:
      /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/src/pybind.cpp:428:58:   required from here
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/pybind11/pybind11.h:1555:7: warning: ‘pybind11::class_<cumc::CUMC<float, int> >’ declared with greater visibility than the type of its field ‘pybind11::class_<cumc::CUMC<float, int> >::<anonymous>’ [-Wattributes]
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/pybind11/pybind11.h:1555:7: warning: ‘pybind11::class_<cumc::CUMC<float, int> >’ declared with greater visibility than its base ‘pybind11::detail::generic_type’ [-Wattributes]
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<cudualmc::CUDMC<double, int> >’:
      /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/src/pybind.cpp:434:66:   required from here
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/pybind11/pybind11.h:1555:7: warning: ‘pybind11::class_<cudualmc::CUDMC<double, int> >’ declared with greater visibility than the type of its field ‘pybind11::class_<cudualmc::CUDMC<double, int> >::<anonymous>’ [-Wattributes]
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/pybind11/pybind11.h:1555:7: warning: ‘pybind11::class_<cudualmc::CUDMC<double, int> >’ declared with greater visibility than its base ‘pybind11::detail::generic_type’ [-Wattributes]
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/pybind11/pybind11.h: In instantiation of ‘class pybind11::class_<cudualmc::CUDMC<float, int> >’:
      /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/src/pybind.cpp:442:64:   required from here
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/pybind11/pybind11.h:1555:7: warning: ‘pybind11::class_<cudualmc::CUDMC<float, int> >’ declared with greater visibility than the type of its field ‘pybind11::class_<cudualmc::CUDMC<float, int> >::<anonymous>’ [-Wattributes]
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/pybind11/pybind11.h:1555:7: warning: ‘pybind11::class_<cudualmc::CUDMC<float, int> >’ declared with greater visibility than its base ‘pybind11::detail::generic_type’ [-Wattributes]
      In file included from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules.h:20:0,
                       from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:7,
                       from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:16,
                       from /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/extension.h:5,
                       from /tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/src/pybind.cpp:3:
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h: In instantiation of ‘void torch::nn::ConvNdImpl<D, Derived>::reset_parameters() [with long unsigned int D = 3; Derived = torch::nn::ConvTranspose3dImpl]’:
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:101:21:   required from ‘void torch::nn::ConvNdImpl<D, Derived>::reset() [with long unsigned int D = 3; Derived = torch::nn::ConvTranspose3dImpl]’
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/Exceptions.h:283:8:   required from here
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:110:28: warning: unused variable ‘fan_out’ [-Wunused-variable]
             auto [fan_in, fan_out] = init::_calculate_fan_in_and_fan_out(weight);
                                  ^
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h: In instantiation of ‘void torch::nn::ConvNdImpl<D, Derived>::reset_parameters() [with long unsigned int D = 2; Derived = torch::nn::ConvTranspose2dImpl]’:
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:101:21:   required from ‘void torch::nn::ConvNdImpl<D, Derived>::reset() [with long unsigned int D = 2; Derived = torch::nn::ConvTranspose2dImpl]’
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/Exceptions.h:283:8:   required from here
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:110:28: warning: unused variable ‘fan_out’ [-Wunused-variable]
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h: In instantiation of ‘void torch::nn::ConvNdImpl<D, Derived>::reset_parameters() [with long unsigned int D = 1; Derived = torch::nn::ConvTranspose1dImpl]’:
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:101:21:   required from ‘void torch::nn::ConvNdImpl<D, Derived>::reset() [with long unsigned int D = 1; Derived = torch::nn::ConvTranspose1dImpl]’
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/Exceptions.h:283:8:   required from here
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:110:28: warning: unused variable ‘fan_out’ [-Wunused-variable]
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h: In instantiation of ‘void torch::nn::ConvNdImpl<D, Derived>::reset_parameters() [with long unsigned int D = 3; Derived = torch::nn::Conv3dImpl]’:
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:101:21:   required from ‘void torch::nn::ConvNdImpl<D, Derived>::reset() [with long unsigned int D = 3; Derived = torch::nn::Conv3dImpl]’
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/Exceptions.h:283:8:   required from here
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:110:28: warning: unused variable ‘fan_out’ [-Wunused-variable]
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h: In instantiation of ‘void torch::nn::ConvNdImpl<D, Derived>::reset_parameters() [with long unsigned int D = 2; Derived = torch::nn::Conv2dImpl]’:
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:101:21:   required from ‘void torch::nn::ConvNdImpl<D, Derived>::reset() [with long unsigned int D = 2; Derived = torch::nn::Conv2dImpl]’
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/Exceptions.h:283:8:   required from here
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:110:28: warning: unused variable ‘fan_out’ [-Wunused-variable]
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h: In instantiation of ‘void torch::nn::ConvNdImpl<D, Derived>::reset_parameters() [with long unsigned int D = 1; Derived = torch::nn::Conv1dImpl]’:
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:101:21:   required from ‘void torch::nn::ConvNdImpl<D, Derived>::reset() [with long unsigned int D = 1; Derived = torch::nn::Conv1dImpl]’
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/Exceptions.h:283:8:   required from here
      /home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:110:28: warning: unused variable ‘fan_out’ [-Wunused-variable]
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 2107, in _run_ninja_build
          subprocess.run(
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-2vzc_w3g/diso_b929849dbf404058be404d6b6f389fa3/setup.py", line 55, in <module>
          setup(
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 91, in run
          _build_ext.run(self)
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 870, in build_extensions
          build_ext.build_extensions(self)
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 252, in build_extension
          _build_ext.build_extension(self, ext)
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 683, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1783, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/ubuntu/miniconda3/envs/dg-mesh/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 2123, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diso
  Running setup.py clean for diso
Failed to build diso
ERROR: Could not build wheels for diso, which is required to install pyproject.toml-based projects
```

**Comment by SarahWeiii** [comment]
I think you need a newer GCC according to the error message `/torch/include/c10/util/C++17.h:13:2: error: #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 9 or later.`

**Comment by tomadonna1** [comment]
did you manged to solve this problem?
